export const DUMMYCARDDATA = [
  {
    id: '1',
    name: 'Product 1',
    price: '$99.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.5,
    totalOrders: 150,
    sale: true,
  },
  {
    id: '2',
    name: 'Product 2',
    price: '$79.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.2,
    totalOrders: 98,
    sale: true,
  },
  {
    id: '3',
    name: 'Product 3',
    price: '$129.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.8,
    totalOrders: 220,
    sale: false,
  },
  {
    id: '4',
    name: 'Product 4',
    price: '$59.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.0,
    totalOrders: 75,
    sale: true,
  },
  {
    id: '5',
    name: 'Product 5',
    price: '$149.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.7,
    totalOrders: 310,
    sale: true,
  },
  {
    id: '6',
    name: 'Product 6',
    price: '$89.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.3,
    totalOrders: 134,
    sale: false,
  },
  {
    id: '7',
    name: 'Product 7',
    price: '$109.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.6,
    totalOrders: 189,
    sale: false,
  },
  {
    id: '8',
    name: 'Product 8',
    price: '$69.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 3.9,
    totalOrders: 64,
    sale: true,
  },
  {
    id: '9',
    name: 'Product 9',
    price: '$199.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.9,
    totalOrders: 402,
    sale: false,
  },
  {
    id: '10',
    name: 'Product 10',
    price: '$54.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.1,
    totalOrders: 88,
    sale: true,
  },
  {
    id: '11',
    name: 'Product 11',
    price: '$119.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.4,
    totalOrders: 176,
    sale: true,
  },
  {
    id: '12',
    name: 'Product 12',
    price: '$39.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 3.8,
    totalOrders: 52,
    sale: true,
  },
  {
    id: '13',
    name: 'Product 13',
    price: '$89.49',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.2,
    totalOrders: 121,
    sale: false,
  },
  {
    id: '14',
    name: 'Product 14',
    price: '$159.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.7,
    totalOrders: 265,
    sale: false,
  },
  {
    id: '15',
    name: 'Product 15',
    price: '$74.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.0,
    totalOrders: 93,
    sale: false,
  },
  {
    id: '16',
    name: 'Product 16',
    price: '$134.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.6,
    totalOrders: 210,
    sale: false,
  },
  {
    id: '17',
    name: 'Product 17',
    price: '$64.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 3.9,
    totalOrders: 70,
    sale: true,
  },
  {
    id: '18',
    name: 'Product 18',
    price: '$179.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.8,
    totalOrders: 340,
    sale: true,
  },
  {
    id: '19',
    name: 'Product 19',
    price: '$49.99',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.1,
    totalOrders: 81,
    sale: false,
  },
  {
    id: '20',
    name: 'Product 20',
    price: '$99.49',
    image: require('../assets/images/dashboardCouple.png'),
    rating: 4.5,
    totalOrders: 158,
    sale: true,
  },
];
