export const DUMMYCARDDATA = [
  {
    id: '1',
    name: 'Classic Cotton T-Shirt',
    brand: 'UrbanWear',
    category: 'Clothing',
    sku: 'UW-001',
    price: 99.99,
    discountPercent: 40,
    finalPrice: 59.99,
    rating: 4.5,
    reviewsCount: 124,
    totalOrders: 150,
    stock: 32,
    sale: true,
    image: require('../assets/images/Frame1.png'),
    description:
      '100% premium cotton, perfect for daily wear with exceptional comfort.',
    availableColors: ['red', 'green', 'blue'],
    tags: ['Best Seller', 'Trending'],
    shippingInfo: 'Free delivery in 3–5 business days',
    returnPolicy: '7-day easy return',
    createdAt: '2024-12-01',
  },
  {
    id: '2',
    name: 'Slim Fit Jeans',
    brand: 'DenimCraft',
    category: 'Bottom Wear',
    sku: 'DC-201',
    price: 89.99,
    discountPercent: 25,
    finalPrice: 67.49,
    rating: 4.3,
    reviewsCount: 89,
    totalOrders: 112,
    stock: 45,
    sale: true,
    image: require('../assets/images/jeans1.png'),
    description: 'Stretch denim with modern slim fit design',
    availableColors: ['indigo', 'black', 'gray'],
    tags: ['New Arrival', 'Premium'],
    shippingInfo: 'Free shipping over $50',
    returnPolicy: '30-day return',
    createdAt: '2024-11-15',
  },
  {
    id: '3',
    name: 'Wireless Headphones Pro',
    brand: 'AudioTech',
    category: 'Electronics',
    sku: 'AT-301',
    price: 249.99,
    discountPercent: 15,
    finalPrice: 212.49,
    rating: 4.8,
    reviewsCount: 256,
    totalOrders: 310,
    stock: 18,
    sale: true,
    image: require('../assets/images/headphones1.png'),
    description: 'Noise cancelling with 40-hour battery life',
    availableColors: ['black', 'white', 'blue'],
    tags: ['Best Seller', 'Premium'],
    shippingInfo: 'Free 2-day delivery',
    returnPolicy: '60-day warranty',
    createdAt: '2024-10-20',
  },
  {
    id: '4',
    name: 'Leather Office Chair',
    brand: 'FurnitureHub',
    category: 'Furniture',
    sku: 'FH-401',
    price: 399.99,
    discountPercent: 30,
    finalPrice: 279.99,
    rating: 4.6,
    reviewsCount: 178,
    totalOrders: 210,
    stock: 8,
    sale: true,
    image: require('../assets/images/chair1.png'),
    description: 'Ergonomic design with lumbar support',
    availableColors: ['brown', 'black'],
    tags: ['Ergonomic', 'Office'],
    shippingInfo: 'Free assembly & delivery',
    returnPolicy: '90-day return',
    createdAt: '2024-09-10',
  },
  {
    id: '5',
    name: 'Fitness Tracker Max',
    brand: 'FitGear',
    category: 'Wearables',
    sku: 'FG-501',
    price: 129.99,
    discountPercent: 20,
    finalPrice: 103.99,
    rating: 4.4,
    reviewsCount: 342,
    totalOrders: 425,
    stock: 60,
    sale: true,
    image: require('../assets/images/tracker1.png'),
    description: 'Heart rate monitor with GPS tracking',
    availableColors: ['black', 'pink', 'blue'],
    tags: ['Fitness', 'Smart'],
    shippingInfo: 'Free shipping',
    returnPolicy: '1-year warranty',
    createdAt: '2024-11-05',
  },
  {
    id: '6',
    name: 'Ceramic Coffee Mug Set',
    brand: 'HomeEssentials',
    category: 'Home & Kitchen',
    sku: 'HE-601',
    price: 34.99,
    discountPercent: null,
    finalPrice: 34.99,
    rating: 4.7,
    reviewsCount: 156,
    totalOrders: 189,
    stock: 120,
    sale: false,
    image: require('../assets/images/mug1.png'),
    description: 'Set of 4 microwave-safe ceramic mugs',
    availableColors: ['white', 'blue', 'gray'],
    tags: ['Kitchen', 'Essential'],
    shippingInfo: 'Standard shipping 5-7 days',
    returnPolicy: '30-day return',
    createdAt: '2024-10-15',
  },
  {
    id: '7',
    name: 'Gaming Laptop RTX 4070',
    brand: 'TechPro',
    category: 'Computers',
    sku: 'TP-701',
    price: 1599.99,
    discountPercent: 10,
    finalPrice: 1439.99,
    rating: 4.9,
    reviewsCount: 89,
    totalOrders: 102,
    stock: 5,
    sale: true,
    image: require('../assets/images/laptop1.png'),
    description: '16GB RAM, 1TB SSD, RTX 4070 GPU',
    availableColors: ['black'],
    tags: ['Gaming', 'Premium'],
    shippingInfo: 'Free expedited shipping',
    returnPolicy: '30-day return',
    createdAt: '2024-12-05',
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    brand: 'WellnessPlus',
    category: 'Fitness',
    sku: 'WP-801',
    price: 49.99,
    discountPercent: 35,
    finalPrice: 32.49,
    rating: 4.2,
    reviewsCount: 234,
    totalOrders: 278,
    stock: 85,
    sale: true,
    image: require('../assets/images/yogamat1.png'),
    description: 'Non-slip eco-friendly yoga mat',
    availableColors: ['purple', 'blue', 'green'],
    tags: ['Eco-friendly', 'Fitness'],
    shippingInfo: 'Free delivery',
    returnPolicy: '60-day return',
    createdAt: '2024-11-20',
  },
  {
    id: '9',
    name: 'Smartphone 256GB',
    brand: 'MobiTech',
    category: 'Electronics',
    sku: 'MT-901',
    price: 899.99,
    discountPercent: null,
    finalPrice: 899.99,
    rating: 4.5,
    reviewsCount: 567,
    totalOrders: 645,
    stock: 25,
    sale: false,
    image: require('../assets/images/phone1.png'),
    description: 'Triple camera, 120Hz display',
    availableColors: ['black', 'white', 'gold'],
    tags: ['Latest', 'Flagship'],
    shippingInfo: 'Free overnight delivery',
    returnPolicy: '14-day return',
    createdAt: '2024-10-01',
  },
  {
    id: '10',
    name: 'Winter Jacket Thermal',
    brand: 'OutdoorGear',
    category: 'Outdoor',
    sku: 'OG-1001',
    price: 199.99,
    discountPercent: 40,
    finalPrice: 119.99,
    rating: 4.6,
    reviewsCount: 189,
    totalOrders: 223,
    stock: 15,
    sale: true,
    image: require('../assets/images/jacket1.png'),
    description: 'Waterproof with thermal insulation',
    availableColors: ['navy', 'black', 'red'],
    tags: ['Winter', 'Waterproof'],
    shippingInfo: 'Free 3-5 day delivery',
    returnPolicy: '90-day return',
    createdAt: '2024-09-25',
  },
  {
    id: '11',
    name: 'Blender Pro 1000W',
    brand: 'KitchenMaster',
    category: 'Appliances',
    sku: 'KM-1101',
    price: 129.99,
    discountPercent: 25,
    finalPrice: 97.49,
    rating: 4.3,
    reviewsCount: 278,
    totalOrders: 321,
    stock: 42,
    sale: true,
    image: require('../assets/images/blender1.png'),
    description: '1000W motor with 8-speed settings',
    availableColors: ['black', 'red'],
    tags: ['Kitchen', 'Powerful'],
    shippingInfo: 'Free shipping',
    returnPolicy: '2-year warranty',
    createdAt: '2024-10-30',
  },
  {
    id: '12',
    name: 'Running Shoes Air',
    brand: 'SportFlex',
    category: 'Footwear',
    sku: 'SF-1201',
    price: 149.99,
    discountPercent: null,
    finalPrice: 149.99,
    rating: 4.7,
    reviewsCount: 456,
    totalOrders: 512,
    stock: 28,
    sale: false,
    image: require('../assets/images/shoes1.png'),
    description: 'Lightweight with superior cushioning',
    availableColors: ['white/black', 'blue/white', 'gray'],
    tags: ['Running', 'Comfort'],
    shippingInfo: 'Free delivery',
    returnPolicy: '60-day return',
    createdAt: '2024-11-10',
  },
  {
    id: '13',
    name: 'Desk Lamp LED',
    brand: 'LightWorks',
    category: 'Home Office',
    sku: 'LW-1301',
    price: 39.99,
    discountPercent: 20,
    finalPrice: 31.99,
    rating: 4.1,
    reviewsCount: 134,
    totalOrders: 156,
    stock: 95,
    sale: true,
    image: require('../assets/images/lamp1.png'),
    description: 'Adjustable brightness with USB port',
    availableColors: ['white', 'black'],
    tags: ['LED', 'Adjustable'],
    shippingInfo: 'Standard shipping',
    returnPolicy: '30-day return',
    createdAt: '2024-12-03',
  },
  {
    id: '14',
    name: 'Backpack Waterproof',
    brand: 'TravelSmart',
    category: 'Bags',
    sku: 'TS-1401',
    price: 79.99,
    discountPercent: 15,
    finalPrice: 67.99,
    rating: 4.4,
    reviewsCount: 289,
    totalOrders: 334,
    stock: 50,
    sale: true,
    image: require('../assets/images/backpack1.png'),
    description: '30L capacity with laptop compartment',
    availableColors: ['black', 'blue', 'gray'],
    tags: ['Waterproof', 'Travel'],
    shippingInfo: 'Free shipping',
    returnPolicy: '1-year warranty',
    createdAt: '2024-10-18',
  },
  {
    id: '15',
    name: 'Watch Classic Silver',
    brand: 'TimeCraft',
    category: 'Accessories',
    sku: 'TC-1501',
    price: 299.99,
    discountPercent: null,
    finalPrice: 299.99,
    rating: 4.8,
    reviewsCount: 178,
    totalOrders: 195,
    stock: 12,
    sale: false,
    image: require('../assets/images/watch1.png'),
    description: 'Automatic movement with sapphire crystal',
    availableColors: ['silver', 'gold'],
    tags: ['Luxury', 'Automatic'],
    shippingInfo: 'Free insured shipping',
    returnPolicy: '2-year warranty',
    createdAt: '2024-09-05',
  },
  {
    id: '16',
    name: 'Air Purifier HEPA',
    brand: 'AirPure',
    category: 'Home Appliances',
    sku: 'AP-1601',
    price: 189.99,
    discountPercent: 30,
    finalPrice: 132.99,
    rating: 4.5,
    reviewsCount: 223,
    totalOrders: 267,
    stock: 20,
    sale: true,
    image: require('../assets/images/purifier1.png'),
    description: 'Covers up to 500 sq ft room',
    availableColors: ['white'],
    tags: ['HEPA', 'Air Quality'],
    shippingInfo: 'Free delivery',
    returnPolicy: '3-year warranty',
    createdAt: '2024-11-25',
  },
  {
    id: '17',
    name: 'Graphic Tablet Pro',
    brand: 'DesignTech',
    category: 'Electronics',
    sku: 'DT-1701',
    price: 349.99,
    discountPercent: 20,
    finalPrice: 279.99,
    rating: 4.6,
    reviewsCount: 156,
    totalOrders: 178,
    stock: 9,
    sale: true,
    image: require('../assets/images/tablet1.png'),
    description: '8192 pressure levels, 10x6 inches',
    availableColors: ['black'],
    tags: ['Professional', 'Design'],
    shippingInfo: 'Free shipping',
    returnPolicy: '1-year warranty',
    createdAt: '2024-10-12',
  },
  // -------------------- 17 completed
  {
    id: '18',
    name: 'Cookware Set 10-Piece',
    brand: 'ChefSelect',
    category: 'Kitware',
    sku: 'CS-1801',
    price: 249.99,
    discountPercent: 35,
    finalPrice: 162.49,
    rating: 4.7,
    reviewsCount: 345,
    totalOrders: 412,
    stock: 35,
    sale: true,
    image: require('../assets/images/cookware1.png'),
    description: 'Non-stick ceramic coating',
    availableColors: ['black', 'red'],
    tags: ['Non-stick', 'Complete Set'],
    shippingInfo: 'Free shipping',
    returnPolicy: 'Lifetime warranty',
    createdAt: '2024-11-08',
  },
  {
    id: '19',
    name: 'Gaming Mouse Wireless',
    brand: 'GameGear',
    category: 'Gaming',
    sku: 'GG-1901',
    price: 79.99,
    discountPercent: null,
    finalPrice: 79.99,
    rating: 4.4,
    reviewsCount: 412,
    totalOrders: 489,
    stock: 65,
    sale: false,
    image: require('../assets/images/mouse1.png'),
    description: '16000 DPI, 6 programmable buttons',
    availableColors: ['black', 'white', 'rgb'],
    tags: ['Gaming', 'Wireless'],
    shippingInfo: 'Free delivery',
    returnPolicy: '2-year warranty',
    createdAt: '2024-12-10',
  },
  {
    id: '20',
    name: 'Sunglasses Polarized',
    brand: 'SunGuard',
    category: 'Accessories',
    sku: 'SG-2001',
    price: 129.99,
    discountPercent: 40,
    finalPrice: 77.99,
    rating: 4.3,
    reviewsCount: 189,
    totalOrders: 223,
    stock: 75,
    sale: true,
    image: require('../assets/images/sunglasses1.png'),
    description: 'UV400 protection with polarized lenses',
    availableColors: ['black', 'brown', 'gray'],
    tags: ['Polarized', 'UV Protection'],
    shippingInfo: 'Free shipping',
    returnPolicy: '30-day return',
    createdAt: '2024-09-30',
  },
  {
    id: '21',
    name: 'Electric Toothbrush',
    brand: 'OralCare',
    category: 'Personal Care',
    sku: 'OC-2101',
    price: 89.99,
    discountPercent: 25,
    finalPrice: 67.49,
    rating: 4.6,
    reviewsCount: 512,
    totalOrders: 589,
    stock: 120,
    sale: true,
    image: require('../assets/images/toothbrush1.png'),
    description: '5 brushing modes with timer',
    availableColors: ['white', 'black', 'blue'],
    tags: ['Dental', 'Electric'],
    shippingInfo: 'Free shipping',
    returnPolicy: '2-year warranty',
    createdAt: '2024-11-18',
  },
  {
    id: '22',
    name: 'Portable Speaker',
    brand: 'SoundWave',
    category: 'Audio',
    sku: 'SW-2201',
    price: 119.99,
    discountPercent: null,
    finalPrice: 119.99,
    rating: 4.5,
    reviewsCount: 278,
    totalOrders: 312,
    stock: 42,
    sale: false,
    image: require('../assets/images/speaker1.png'),
    description: '360° sound, 20-hour battery',
    availableColors: ['black', 'blue', 'red'],
    tags: ['Portable', 'Bluetooth'],
    shippingInfo: 'Free shipping',
    returnPolicy: '1-year warranty',
    createdAt: '2024-10-22',
  },
  {
    id: '23',
    name: 'Hiking Boots Pro',
    brand: 'TrailMaster',
    category: 'Footwear',
    sku: 'TM-2301',
    price: 169.99,
    discountPercent: 30,
    finalPrice: 118.99,
    rating: 4.7,
    reviewsCount: 189,
    totalOrders: 201,
    stock: 22,
    sale: true,
    image: require('../assets/images/boots1.png'),
    description: 'Waterproof with ankle support',
    availableColors: ['brown', 'black'],
    tags: ['Hiking', 'Waterproof'],
    shippingInfo: 'Free delivery',
    returnPolicy: '90-day return',
    createdAt: '2024-09-15',
  },
  {
    id: '24',
    name: 'Monitor 27" 4K',
    brand: 'DisplayPro',
    category: 'Electronics',
    sku: 'DP-2401',
    price: 429.99,
    discountPercent: 20,
    finalPrice: 343.99,
    rating: 4.8,
    reviewsCount: 156,
    totalOrders: 178,
    stock: 14,
    sale: true,
    image: require('../assets/images/monitor1.png'),
    description: '4K UHD, 144Hz refresh rate',
    availableColors: ['black'],
    tags: ['4K', 'Gaming'],
    shippingInfo: 'Free shipping',
    returnPolicy: '3-year warranty',
    createdAt: '2024-11-30',
  },
  {
    id: '25',
    name: 'Coffee Maker Smart',
    brand: 'BrewMaster',
    category: 'Appliances',
    sku: 'BM-2501',
    price: 159.99,
    discountPercent: 15,
    finalPrice: 135.99,
    rating: 4.4,
    reviewsCount: 234,
    totalOrders: 278,
    stock: 30,
    sale: true,
    image: require('../assets/images/coffeemaker1.png'),
    description: 'Programmable with grinder',
    availableColors: ['stainless', 'black'],
    tags: ['Smart', 'Coffee'],
    shippingInfo: 'Free shipping',
    returnPolicy: '2-year warranty',
    createdAt: '2024-10-08',
  },
  {
    id: '26',
    name: 'Yoga Pants High-Waist',
    brand: 'ActiveWear',
    category: 'Fitness Wear',
    sku: 'AW-2601',
    price: 59.99,
    discountPercent: null,
    finalPrice: 59.99,
    rating: 4.6,
    reviewsCount: 456,
    totalOrders: 523,
    stock: 85,
    sale: false,
    image: require('../assets/images/yogapants1.png'),
    description: '4-way stretch, moisture-wicking',
    availableColors: ['black', 'gray', 'blue'],
    tags: ['Yoga', 'Comfort'],
    shippingInfo: 'Free shipping',
    returnPolicy: '30-day return',
    createdAt: '2024-12-01',
  },
  {
    id: '27',
    name: 'Drone Camera 4K',
    brand: 'SkyView',
    category: 'Electronics',
    sku: 'SV-2701',
    price: 799.99,
    discountPercent: 25,
    finalPrice: 599.99,
    rating: 4.7,
    reviewsCount: 123,
    totalOrders: 145,
    stock: 8,
    sale: true,
    image: require('../assets/images/drone1.png'),
    description: '30-min flight time, 4K camera',
    availableColors: ['black', 'white'],
    tags: ['Drone', 'Camera'],
    shippingInfo: 'Free insured shipping',
    returnPolicy: '1-year warranty',
    createdAt: '2024-09-28',
  },
  {
    id: '28',
    name: 'Weight Set Adjustable',
    brand: 'FitStrong',
    category: 'Fitness',
    sku: 'FS-2801',
    price: 199.99,
    discountPercent: 20,
    finalPrice: 159.99,
    rating: 4.3,
    reviewsCount: 89,
    totalOrders: 102,
    stock: 25,
    sale: true,
    image: require('../assets/images/weights1.png'),
    description: '5-50 lbs adjustable dumbbells',
    availableColors: ['black'],
    tags: ['Weights', 'Adjustable'],
    shippingInfo: 'Free shipping',
    returnPolicy: '5-year warranty',
    createdAt: '2024-11-12',
  },
  {
    id: '29',
    name: 'Perfume Luxury Edition',
    brand: 'ScentCraft',
    category: 'Fragrance',
    sku: 'SC-2901',
    price: 149.99,
    discountPercent: null,
    finalPrice: 149.99,
    rating: 4.8,
    reviewsCount: 278,
    totalOrders: 312,
    stock: 45,
    sale: false,
    image: require('../assets/images/perfume1.png'),
    description: 'Long-lasting premium fragrance',
    availableColors: ['clear'],
    tags: ['Luxury', 'Fragrance'],
    shippingInfo: 'Free shipping',
    returnPolicy: '30-day return',
    createdAt: '2024-10-25',
  },
  {
    id: '30',
    name: 'Standing Desk Electric',
    brand: 'WorkSmart',
    category: 'Furniture',
    sku: 'WS-3001',
    price: 499.99,
    discountPercent: 35,
    finalPrice: 324.99,
    rating: 4.9,
    reviewsCount: 178,
    totalOrders: 195,
    stock: 12,
    sale: true,
    image: require('../assets/images/desk1.png'),
    description: 'Height adjustable with memory presets',
    availableColors: ['white', 'black', 'walnut'],
    tags: ['Ergonomic', 'Adjustable'],
    shippingInfo: 'Free assembly & delivery',
    returnPolicy: '10-year warranty',
    createdAt: '2024-09-20',
  },
];
